In [ ]:
import altair as alt
import pandas as pd

# Abrindo csv's

In [ ]:
df25 = pd.read_csv('cleaned_data.csv') # Dados do Salário Transparente de 2025
df26 = pd.read_csv('raw_data.csv', sep=';') # Dados do Salário Transparente de 2026

In [ ]:
df25

,cargo,empresa,salario_base,localizacao,modalidade_trabalho,nivel,experiencia,tipo_contrato,remuneracao_total_anual,remuneracao_inclui,...,Previdência privada,Seguro de vida,Stock Options,Vale Alimentação,Vale Refeição,Vale Transporte,Vale-alimentação,Vale-refeição,Viagens,estado
0,Data Scientist,Ambev Tech,15.300,"Salvador, Bahia",Remoto,Sênior,6 anos de experiência,CLT,248.949,"Inclui bônus, PLR, stock options e comissões",...,nao,nao,nao,sim,sim,nao,nao,nao,nao,BA
1,Data Scientist,Hospital Albert Einstein,15.000,"São Paulo, São Paulo",Híbrido,Sênior,6 anos de experiência,CLT,199.950,"Inclui bônus, PLR, stock options e comissões",...,nao,nao,nao,sim,sim,nao,nao,nao,nao,SP
2,Data Scientist,Hospital Albert Einstein,21.606,"São Paulo, São Paulo",Híbrido,Sênior,7 anos de experiência,CLT,332.008,"Inclui bônus, PLR, stock options e comissões",...,nao,nao,nao,sim,sim,nao,nao,nao,nao,SP
3,Data Scientist,Serasa,7.000,"São Paulo, São Paulo",Híbrido,Pleno,3 anos de experiência,CLT,105.910,"Inclui bônus, PLR, stock options e comissões",...,sim,sim,sim,sim,sim,sim,nao,nao,nao,SP
4,Data Scientist,John Snow Labs,40.000,"São Paulo, São Paulo",Remoto,Sênior,8 anos de experiência,PJ,480.000,"Inclui bônus, PLR, stock options e comissões",...,nao,nao,nao,nao,nao,nao,nao,nao,nao,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,Data Analyst,PicPay,9.000,"São Paulo, São Paulo",Híbrido,Pleno,3 anos de experiência,CLT,119.970,"Inclui bônus, PLR, stock options e comissões",...,nao,sim,nao,sim,nao,sim,nao,nao,nao,SP
493,Analyst and Products,Cia. Hering,7.665,"São Paulo, São Paulo",Remoto,Sênior,4 anos de experiência,CLT,105.674,"Inclui bônus, PLR, stock options e comissões",...,sim,sim,nao,sim,sim,nao,nao,nao,sim,SP
494,Data Analyst,Capgemini,2.200,Minas Gerais,Remoto,Júnior,1 ano de experiência,CLT,29.326,"Inclui bônus, PLR, stock options e comissões",...,sim,sim,nao,sim,nao,sim,nao,nao,nao,MG
495,Data Analyst,Loggi,14.000,"Brasília, Distrito Federal",Remoto,Sênior,5 anos de experiência,CLT,252.620,"Inclui bônus, PLR, stock options e comissões",...,nao,sim,sim,sim,sim,nao,nao,nao,nao,DF
496,Data Analyst,99,12.000,"São Paulo, São Paulo",Híbrido,Sênior,2 anos de experiência,CLT,189.960,"Inclui bônus, PLR, stock options e comissões",...,nao,sim,nao,sim,sim,nao,nao,nao,sim,SP

In [ ]:
df26

,cargo,empresa,salario_base,localizacao,modalidade_trabalho,nivel,experiencia,tipo_contrato,remuneracao_total_anual,remuneracao_total_mensal,remuneracao_inclui,salario_base_detalhado,bonus_anual,relacao_empresa,area_especializacao,beneficios
0,Analista de Dados,TCS,4.700,"Extremoz, Rio Grande do Norte",Remoto,Júnior,2.9 anos de experiência,CLT,62.651,5.221,"Inclui bônus, PLR, stock options e comissões",62.651,Não informado,Oferta de emprego recebida em abril de 2025,Power BI,Vale Refeição | Vale Alimentação | Vale Transp...
1,Analista de Dados,iFood,15.000,"São Paulo, São Paulo",Remoto,Sênior,8 anos de experiência,CLT,227.950,18.996,"Inclui bônus, PLR, stock options e comissões",199.950,28.000,Funcionário em maio de 2026,Inteligência Artificial / Machine Learning,Vale Refeição | Vale Alimentação | Auxílio Edu...
2,Analista de Dados S,Alloha Fibra,7.069,"São Paulo, São Paulo",Presencial,Sênior,2 anos de experiência,CLT,94.930,7.911,"Inclui bônus, PLR, stock options e comissões",94.230,700,Funcionário em maio de 2026,Inteligência Artificial / Machine Learning,Vale Refeição | Auxílio Internet | Plano de Sa...
3,Analista de Dados,TCS,4.600,"Extremoz, Rio Grande do Norte",Remoto,Júnior,3.5 anos de experiência,CLT,61.318,5.110,"Inclui bônus, PLR, stock options e comissões",61.318,Não informado,Oferta de emprego recebida em fevereiro de 2026,Power BI,Vale Refeição | Vale Alimentação | Vale Transp...
4,Analista de Dados,JHSF,6.300,"São Paulo, São Paulo",Presencial,Pleno,4 anos de experiência,CLT,90.279,7.523,"Inclui bônus, PLR, stock options e comissões",83.979,6.300,Saiu da empresa em 2025 (ex-funcionário),Outra,Vale Refeição | Plano de Saúde | Horário Flexí...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,Engenheiro de Dados,Rox Partner,14.000,São Paulo,Híbrido,Sênior,6 anos de experiência,CLT,186.620,15.552,"Inclui bônus, PLR, stock options e comissões",186.620,Não informado,Funcionário em março de 2025,Não informado,Vale Alimentação | Home Office | Horário Flexí...
370,Engenheiro de Dados,Banco Bradesco,13.500,"Osasco, São Paulo",Híbrido,Sênior,7 anos de experiência,CLT,199.955,16.663,"Inclui bônus, PLR, stock options e comissões",179.955,20.000,Funcionário em março de 2025,Marketing Digital,Vale Refeição | Vale Alimentação | Vale Transp...
371,Engenheiro de Dados,NTT Data,7.777,"Uberlandia, Minas Gerais",Remoto,Sênior,10 anos de experiência,CLT,103.669,8.639,"Inclui bônus, PLR, stock options e comissões",103.669,Não informado,Funcionário em março de 2025,Banco de Dados,Vale Refeição | Vale Alimentação | Plano de Sa...
372,Engenheiro de Dados,Banco Safra,9.841,"São Paulo, São Paulo",Híbrido,Sênior,4 anos de experiência,CLT,171.181,14.265,"Inclui bônus, PLR, stock options e comissões",131.181,40.000,Funcionário em março de 2025,Banco de Dados,Vale Refeição | Vale Alimentação | Auxílio Cre...
373,Engenheiro de Dados,Petlove,5.500,"São Paulo, São Paulo",Remoto,Júnior,2 anos de experiência,CLT,78.815,6.568,"Inclui bônus, PLR, stock options e comissões",73.315,5.500,Funcionário em março de 2025,Banco de Dados,Vale Refeição | Vale Alimentação | Plano de Sa...

# Comparando Salário por Ano

In [ ]:
# Criando uma nova coluna do ano
df25['Ano'] = '2025'
df26['Ano'] = '2026'

# Concatenando os dois data frames
df = pd.concat([df25, df26])

# Tirando outliers de salário pelos quantis
Q1 = df['salario_base'].quantile(0.25)
Q3 = df['salario_base'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR
df = df[(df['salario_base'] >= limite_inferior) & (df['salario_base'] <= limite_superior)]

# Renomeando coluna de salário
df.rename(columns={'salario_base': 'Salário Base (R$)'}, inplace=True)
df['Salário Base (R$)'] *= 1000

In [ ]:
# Plotando Gráfico
chart = alt.Chart(df).mark_boxplot(
    extent='min-max',
    size=60
    ).encode(
    x='Ano:N',
    y='Salário Base (R$):Q',
    color='Ano:N'
).properties(
    title='Comparação de Salário por Ano',
    width=1280,
    height=720
).configure_axis(
    labelFontSize=14,  # Tamanho dos números/rótulos no eixo
    titleFontSize=16   # Tamanho do texto do título do eixo
).configure_legend(
    labelFontSize=14,  # Aumenta o tamanho dos textos dos itens da legenda
    titleFontSize=14,  # Aumenta o tamanho do título da legenda
    symbolSize=150     # Aumenta o tamanho dos ícones/símbolos da legenda
).configure_title(
    fontSize=20     # Altera o tamanho do título do gráfico
)

chart.show()

alt.Chart(...)

# Salário por Tipo de Contrato

In [ ]:
# Tirando os tipos de contrato não especificados
df = df[df['tipo_contrato'] != 'Outro']

# Renomeando a coluna tipo de contrato
df.rename(columns={'tipo_contrato': 'Tipo de Contrato'}, inplace=True)

/tmp/ipykernel_481/1921167890.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'tipo_contrato': 'Tipo de Contrato'}, inplace=True)

In [ ]:
# Plotando Gráfico
chart = alt.Chart(df).mark_boxplot(
    extent='min-max',
    size=60
    ).encode(
    x=alt.X('Tipo de Contrato:N', sort=['PJ', 'CLT', 'Estágio']),
    y='Salário Base (R$):Q',
    color='Tipo de Contrato:N'
).properties(
    title='Salário por Tipo de Contrato',
    width=1280,
    height=720
).configure_axis(
    labelFontSize=14,  # Tamanho dos números/rótulos no eixo
    titleFontSize=16   # Tamanho do texto do título do eixo
).configure_legend(
    labelFontSize=14,  # Aumenta o tamanho dos textos dos itens da legenda
    titleFontSize=14,  # Aumenta o tamanho do título da legenda
    symbolSize=150     # Aumenta o tamanho dos ícones/símbolos da legenda
).configure_title(
    fontSize=20     # Altera o tamanho do título do gráfico
)

chart.show()

alt.Chart(...)

# Salário por Nível

In [ ]:
# Renomeando a coluna de nível
df.rename(columns={'nivel': 'Nível'}, inplace=True)

In [ ]:
# Plotando Gráfico
chart = alt.Chart(df).mark_boxplot(
    extent='min-max',
    size=60
    ).encode(
    x=alt.X('Nível:N', sort=['Líder / Coordenador', 'Especialista', 'Sênior', 'Pleno', 'Júnior', 'Estagiário']),
    y='Salário Base (R$):Q',
    color='Nível:N'
).properties(
    title='Salário por Nível',
    width=1280,
    height=720
).configure_axis(
    labelFontSize=14,  # Tamanho dos números/rótulos no eixo
    titleFontSize=16   # Tamanho do texto do título do eixo
).configure_legend(
    labelFontSize=14,  # Aumenta o tamanho dos textos dos itens da legenda
    titleFontSize=14,  # Aumenta o tamanho do título da legenda
    symbolSize=150     # Aumenta o tamanho dos ícones/símbolos da legenda
).configure_title(
    fontSize=20     # Altera o tamanho do título do gráfico
)

chart.show()

alt.Chart(...)

In [ ]:
# Criando tabela com as médias
media_ordenada = df.groupby('Nível')['Salário Base (R$)'].mean().sort_values(ascending=False).reset_index()

# Formatando os valores
media_ordenada['Salário Base (R$)'] = media_ordenada['Salário Base (R$)'].apply(lambda x: f"R$ {x:,.2f}".replace(",", "X").replace(".", ",").replace("X", "."))

media_ordenada

                 Nível Salário Base (R$)
0  Líder / Coordenador      R$ 17.000,00
1         Especialista      R$ 13.461,53
2               Sênior      R$ 11.435,40
3                Pleno       R$ 8.225,23
4               Júnior       R$ 5.154,59
5           Estagiário       R$ 2.393,86